version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    container_name: course-nodejs-rest-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:27017
    volumes:
      - ./mongodb:/data/db
    command: --wiredTigerCacheSizeGB 2
