@baseUrl = http://localhost:{{$dotenv PORT}}

# Create user
POST {{baseUrl}}/sign-up HTTP/1.1
Content-Type: application/json

{
  "name": "John.Connor",
  "email": "email@mail.com",
  "password": "1234abcd",
  "avatar": "https://9.react.pages.academy/static/avatar/6.jpg",
  "userType": "pro"
}

###

# Login user
POST {{baseUrl}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "email@mail.com",
  "password": "1245abcd"
}

###

# Saving avatar
POST {{baseUrl}}/users/6288a57316071e3025719415/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/gif

< /mnt/f/assets/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# Get offers
GET {{baseUrl}}/offers?count=10 HTTP/1.1
Content-Type: application/json

###

# Get one offer
GET {{baseUrl}}/offers/628cd7811a115553c07c4fff HTTP/1.1
Content-Type: application/json

###

# Create offer
POST {{baseUrl}}/offers HTTP/1.1
Content-Type: application/json

{
  "title": "Loft Studio in the Central Area",
  "description": "Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "date": "2021-05-27T04:10:31.562Z",
  "city": "Hamburg",
  "previewImage": "https://9.react.pages.academy/static/hotel/8.jpg",
  "images": [
    "https://9.react.pages.academy/static/hotel/2.jpg",
    "https://9.react.pages.academy/static/hotel/10.jpg",
    "https://9.react.pages.academy/static/hotel/6.jpg",
    "https://9.react.pages.academy/static/hotel/7.jpg",
    "https://9.react.pages.academy/static/hotel/8.jpg",
    "https://9.react.pages.academy/static/hotel/9.jpg"
  ],
  "isPremium": false,
  "rating": 2.4,
  "type": "hotel",
  "bedrooms": 4,
  "maxGuests": 8,
  "price": 86289,
  "goods": [
    "Baby seat",
    "Breakfast",
    "Fridge",
    "Washer",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "author": "6288a57316071e3025719415",
  "location": { "latitude": 53.473808, "longitude": 10.04526 }
}

###

# Update offer
PUT {{baseUrl}}/offers/628cd7811a115553c07c4fff HTTP/1.1
Content-Type: application/json

{
  "title": "Loft Studio in the Central Area",
  "description": "Design interior in most sympathetic area! Complitely renovated, well-equipped, cosy studio in idyllic, over 100 years old wooden house. Calm street, fast connection to center and airport.",
  "date": "2021-05-27T04:10:31.562Z",
  "city": "Hamburg",
  "previewImage": "https://9.react.pages.academy/static/hotel/8.jpg",
  "images": [
    "https://9.react.pages.academy/static/hotel/2.jpg",
    "https://9.react.pages.academy/static/hotel/10.jpg",
    "https://9.react.pages.academy/static/hotel/6.jpg",
    "https://9.react.pages.academy/static/hotel/7.jpg",
    "https://9.react.pages.academy/static/hotel/8.jpg",
    "https://9.react.pages.academy/static/hotel/9.jpg"
  ],
  "isPremium": false,
  "rating": 0,
  "type": "hotel",
  "bedrooms": 6,
  "maxGuests": 8,
  "price": 86289,
  "goods": [
    "Baby seat",
    "Breakfast",
    "Fridge",
    "Washer",
    "Air conditioning",
    "Laptop friendly workspace"
  ],
  "author": "6288a57316071e3025719415",
  "location": { "latitude": 53.473808, "longitude": 10.04526 }
}

###

# Delete offer
DELETE {{baseUrl}}/offers/6288bb1a26a5f089541fcd1e HTTP/1.1
Content-Type: application/json

###

# Get premium offers
GET {{baseUrl}}/premium HTTP/1.1
Content-Type: application/json
